version: '2.2' 
services:
  app:
    image: domix/mn-data-jdbc:0.1-jre-11-0.4
    cpus: 0.5
    mem_reservation: 512m
    ports:
      - 8099:8080
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/comparison
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_DB=comparison
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432