apiVersion: v1
kind: Pod
metadata:
  name: cassandra-load-keyspace
spec:
  containers:
    - name: cassandra-load-keyspace
      image: restrada/cassandra-load-keyspace:latest
      imagePullPolicy: IfNotPresent
      command: ["cqlsh", "cassandra", "-f", "schema.cql"]
  restartPolicy: Never